### ISSUE TITLE
NullPointerException in AbstractTTTLearner.splitState()

### ISSUE THREAD

**Issue by cgvwzq** [LearnLib/learnlib#66]
I'm getting a crash when using the TTT learner, it happens with different settings (for some configurations of caching and ce analyzer the crash is delayed or even disappears), so it seems to depend on the specific ce. I use WpMethod to make it more deterministic.

The issue might be related to https://github.com/LearnLib/learnlib/issues/36.

I tried both refineHypothesis and refineHypothesisSingle.

Stack trace:

```Caused by: java.lang.NullPointerException
	at de.learnlib.algorithms.ttt.base.AbstractTTTLearner.splitState(AbstractTTTLearner.java:244)
	at de.learnlib.algorithms.ttt.base.AbstractTTTLearner.splitState(AbstractTTTLearner.java:285)
	at de.learnlib.algorithms.ttt.base.AbstractTTTLearner.refineHypothesisSingle(AbstractTTTLearner.java:215)
	at de.learnlib.algorithms.ttt.mealy.TTTLearnerMealy.refineHypothesisSingle(TTTLearnerMealy.java:67)
	at xxxx.XXXX.run(XXXX.java:281)
	at xxxx.XXXX.main(XXXX.java:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
```

Some notes:
* The main difference I observe before a crash is that `splitSuffix` in `splitState() (AbstractTTTLearner.java:259)` is just 1 symbol shorter than `suffix`.
* Assertions `trans.isTree()` fail at `AbstractTTTLearner.splitState(AbstractTTTLearner.java:275)`.
* Then `TTTTransition.getNonTreeTarget()` returns `null` at`AbstractTTTLearner.splitState(AbstractTTTLearner.java:239)`
* And `dtNode.getData()` crashes at `AbstractTTTLearner.splitState(AbstractTTTLearner.java:241)`

I do not understand how the TTT algorithm works, so right now I'm quite clueless about what's happening. I'll try reading the paper to see what the tree vs. non-tree transition are, but any help is welcome.

Thanks for you great work!

**Comment by mtf90** [comment]
Which version of LearnLib are you using? When analyzing your stacktrace it doesn't seem to match with either the `0.14.0` or the current `develop` codebase.

* On `0.14.0`, `AbstractTTTLearner.java:215` invokes `closeTransitions()` and `AbstractTTTLearner.java:285` is somewhere in `deriveAcex()` and
* on `develop`, `AbstractTTTLearner.java:215` invokes `findOutputInconsistency()` and `AbstractTTTLearner.java:285` is again somewhere in `deriveAcex()`.

**Comment by mtf90** [comment]
Any updates on this?

**Comment by cgvwzq** [comment]
Sorry, I forgot about this. I was using 0.14.0 release, the incosistency might be due to some lines I added for debugging.

I'm not being able to reproduce the crash anymore, but if I encounter the issue again I'll try report with test case. Feel free to close.

**Comment by mtf90** [comment]
Thanks for the feedback. Feel free to re-open this issue then.
